# Generated by Django 3.1.6 on 2022-05-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220512_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='DA',
            new_name='Date_Abonnement',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='NA',
            new_name='Numero_Abonnement',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='OA',
            new_name='Option_Abonnement',
        ),
    ]
