# Generated by Django 3.1.6 on 2022-05-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220512_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='Nom',
        ),
    ]
